"""Washington State outline -> SVG path for the map shot (remotion-lab/src/olympia/waMap.ts).
Source: johan/world.geo.json countries/USA/WA.geo.json (public domain, UNLICENSE), a low-detail
outline that includes Puget Sound. Equirectangular projection with cos(47 deg) x-scaling."""
import json, math
d = json.load(open("assets/WA.geo.json"))
polys = d["features"][0]["geometry"]["coordinates"]
k = math.cos(math.radians(47.3))
lon0, lon1, lat0, lat1 = -124.9, -116.8, 45.5, 49.1
W = 900; S = W / ((lon1 - lon0) * k); H = round((lat1 - lat0) * S)
P = lambda lon, lat: (round((lon - lon0) * k * S, 1), round((lat1 - lat) * S, 1))
paths = []
for poly in polys:
    ring = poly[0]
    pts = [P(*p) for p in ring]
    paths.append("M" + " L".join(f"{x} {y}" for x, y in pts) + " Z")
cities = {"olympia": P(-122.9007, 47.0379), "seattle": P(-122.3321, 47.6062)}
open("../remotion-lab/src/olympia/waMap.ts", "w").write(
    "// generated by olympia/src/make_map.py - Washington outline (public-domain world.geo.json), equirectangular\n"
    f"export const WA_W = {W};\nexport const WA_H = {H};\nexport const WA_PATHS = {json.dumps(paths)};\n"
    f"export const OLYMPIA = {{ x: {cities['olympia'][0]}, y: {cities['olympia'][1]} }};\n"
    f"export const SEATTLE = {{ x: {cities['seattle'][0]}, y: {cities['seattle'][1]} }};\n")
print(W, H, cities)
